### ISSUE TITLE
Refactor to use svelte.compile and svelte.preprocess

### ISSUE THREAD

**Issue by matthew-ia** [matthew-ia/cayo#50]
**Todo:** 
- [ ] preprocess and compile as a part of the prerender pages
- [ ] preprocess and compile Cayo Components and save them to a file for runtime
- [ ] pass preprocess settings from config to any instance of `svelte.preprocess`
- [ ] Optimize watching pages and components, and re-prerender pages when their components get updated
- [ ] Catch svelte.compile errors and warnings and report them without exiting

**Related Issues:**
- #42
- #46 
- #28 
- #49

**Comment by matthew-ia** [comment]
Something big to consider is that the `.cayo/pages.js` file was also intended to help be able to force a cache refresh on all the page modules, so they weren't stale between building the prerendered pages.

**Comment by matthew-ia** [comment]
In order to get svelte-process goodness for all components and pages, _every_ component, whether it's a dependency of a page or just another component, will need to be compiled the new way. 

That means I'll need to maintain some sort of dependency tree, just for knowing what does/doesn't need to be compiled when the watcher detects a change in a particular Svelte component. Something like:


```js
// I'm thinking the key is the dependee, and its value is an array of its dependers
const dependees = {
  '/path/to/component1.svelte': ['/path/to/component2.svelte', '/path/to/page1.svelte'],
  '/path/to/component2.svelte': ['/path/to/component3.svelte', '/path/to/page2.svelte'],
  '/path/to/component3.svelte': [], // empty array if no dependers
}
```

Just regarding the inner component dependencies: In this case, 2 has 1 in it. 3 has 2 in it. So technically, 3 has two dependees: 2 and 1. Need to figure out how to solve for that too, "nested" dependencies **n** levels deep. Also note: if a dependee has no dependers, it doesn't need to be compiled, even if it's a depender of something else. So 3 doesn't actually need to get compiled.

The upside down tree, I was thinking would be useful because you could see: ok this component was modified, `dependees[watchedPath]` would get you the list of things you now have to recompile because of that change. But, I feel like the nested deps thing is where that gets tricky, because it's easier to derive the nested ones from a top-down tree, I think (key being the depender, dependee as array elements).

---

Also need a flat list of all things that were compiled per refresh, so that unchanged dependencies of multiple Svelte components don't have to be recompiled if they were already compiled due to another dependency relationship.

**Comment by matthew-ia** [comment]
Would it make sense to put the logic of resolveImports into a custom preprocessor, and pass that as a function to `svelte.preprocess`? I think it'd be cleaner, and aligns with the "svelte" way (it's doing exactly what a custom preprocessor would, but after compilation, even though it doesn't _need_ to happen afterward).

**Comment by matthew-ia** [comment]
[Flow Chart for the new process](https://www.figma.com/file/dJ4WAsvwX3AVhto4E0p6om/Cayo-Flow?node-id=3%3A43)

**Comment by matthew-ia** [comment]
The stale module issue is still around even after a good majority of the rewrite. 

page modules recompile/render their local contents fine, but their external dependencies, even though the deps themselves are updating, the instance is getting stale versions of the modules. 

E.g., Page uses component A. Module A gets updated when user changes the source file (A.svelte). But Page does not see the changes even tho it also re-renders after it is recompiled and reloaded via dynamic import. 

I think the fix may be to move the external dependencies into the page module, so their are no external deps. This wouldn't be too hard I don't think, since I have each file and could just copy it directly into the file but wrapped in a function to call instead of the imported object. Pretty confident that'd work.

**Comment by matthew-ia** [comment]
why can't we just use rollup at these steps instead of svelte.preprocess & svelte.compile??? I think I shied away from it just bc the rollup setup I initially had didn't work well. 

Preprocess > compile was the main concern, but that'  what rollup can do with the right plugins, it just _also_ bundles.

**Comment by matthew-ia** [comment]
Biggest problem with using just `rollup` is figuring out how to reorgnize the processing that was done on the source code before/after compilation in the original flow. 


I think `svelte.preprocess` with custom preprocessors can help with these:
- [ ] replacing relative paths with absolute paths (we need this since the bundle output is in a diff directory than the source, `src/` vs `.cayo/`)
- [ ] changing cayo ids in the markup from the path strings to their UUID names. E.g., `<div data-cayo-id="./some/path/a.cayo.svelte">` to `<div data-cayo-id="some__path__a-{hash}">`

**Comment by matthew-ia** [comment]
Not sure when/where this issue is from, but right now the only pages that get compiled are the ones you save after running the command. It should compile all of them when starting. 

- [ ] First-time run should compile all pages

**Comment by matthew-ia** [comment]
Since we don't need to compile normal components, change the references for generic `components` to `cayos` or `cayoComponents` (e.g. `compile.components` -> `compile.cayos`

- [ ] Make component-bundling specific to Cayo Components aka `cayos`

**Comment by matthew-ia** [comment]
73394778b4bcb2400c8c843ff6da4ad25b803c99 adds component dependency watching, which triggers a rerender of dependent pages. This as the last big piece of the puzzle.
